"""Sticker plugin:
.q / .qr  — render the replied-to message as a quote sticker via the lyo.su API
.kang     — steal a replied sticker/photo into the user's own auto-growing pack

The quote sticker is generated by the public lyo.su quote API, which draws a
pixel-perfect replica of a Telegram message bubble: circular avatar, peer-
coloured display name, and the message body. This is the same backend used by
the popular "Quote" bots, so the result looks exactly like a real Telegram
message. The .kang command is unchanged (still uses Pillow + DejaVu fonts)."""
import base64
import io
import logging
import os
import re

import aiohttp
from PIL import Image
from telegram import InputSticker
from telegram.error import TelegramError

import database as dbase
from common import T, dual_command, esc, say

log = logging.getLogger("sticker")

HELP_TXT = (
    "<b>✦ stickers</b>\n\n"
    "/q (or .q) — reply to any message to turn it into a quote sticker\n"
    "/qr (or .qr) — same, but sent as a reply to the original message\n"
    "/kang (or .kang) [emoji] — reply to a sticker or photo to add it to your "
    "own sticker pack. the pack is created the first time and reused after that — "
    "every later .kang just adds to it (a new part is started automatically if it fills up)."
)
COMMANDS = [("q", "Quote a message as a sticker"), ("kang", "Steal a sticker into your pack")]

MAX_SIDE = 512
EMOJI_RE = re.compile(r"^[\U0001F000-\U0001FAFF\u2600-\u27BF\u2190-\u21FF\u2B00-\u2BFF]+$")

QUOTE_API = "https://bot.lyo.su/quote/generate"
QUOTE_BG = "#1b1429"  # dark purple background — matches Telegram dark theme


def _fit_512(img: Image.Image) -> Image.Image:
    w, h = img.size
    scale = MAX_SIDE / max(w, h)
    return img.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)


async def _profile_photo_url(ctx, user) -> str:
    """Return a base64 data URI for the user's profile photo, or '' if none.
    The lyo.su API accepts both https URLs and data URIs — data URIs avoid
    exposing the bot token in a public URL."""
    try:
        photos = await ctx.bot.get_user_profile_photos(user.id, limit=1)
        if not photos.total_count:
            return ""
        file_id = photos.photos[0][-1].file_id
        tgfile = await ctx.bot.get_file(file_id)
        raw = await tgfile.download_as_bytearray()
        b64 = base64.b64encode(bytes(raw)).decode()
        return f"data:image/jpeg;base64,{b64}"
    except (TelegramError, OSError) as e:
        log.debug("profile photo fetch failed for %s: %s", user.id, e)
        return ""


async def _build_quote_sticker(ctx, src_msg, sender) -> bytes:
    """Call the lyo.su API and return the resulting .webp bytes."""
    text = src_msg.text or src_msg.caption or ""
    photo_url = await _profile_photo_url(ctx, sender)

    from_block = {
        "id": sender.id,
        "name": sender.first_name or sender.full_name or "User",
        "photo": {"url": photo_url} if photo_url else {},
    }

    payload = {
        "type": "quote",
        "format": "webp",
        "backgroundColor": QUOTE_BG,
        "messages": [
            {
                "entities": [],
                "avatar": True,
                "from": from_block,
                "text": text,
                "replyMessage": {},
            }
        ],
    }

    async with aiohttp.ClientSession() as session:
        async with session.post(QUOTE_API, json=payload, timeout=aiohttp.ClientTimeout(total=30)) as resp:
            if resp.status != 200:
                body = await resp.text()
                raise RuntimeError(f"quote API returned {resp.status}: {body[:200]}")
            return await resp.read()


async def _quote_and_send(update, ctx, as_reply: bool):
    msg, chat = update.effective_message, update.effective_chat
    src = msg.reply_to_message
    if not src:
        await say(ctx, chat.id, T("reply to a message with /q to turn it into a sticker."), reply_to=msg.message_id)
        return
    if not (src.text or src.caption):
        await say(ctx, chat.id, T("only text messages can be quoted."), reply_to=msg.message_id)
        return

    sender = src.from_user or msg.from_user
    status = await say(ctx, chat.id, T("⏳ generating quote..."), reply_to=msg.message_id)

    try:
        sticker_bytes = await _build_quote_sticker(ctx, src, sender)
    except Exception as e:
        log.error("quote generation failed: %s", e)
        try:
            await status.edit_text(T("❌ couldn't build that sticker:") + f" {esc(e)}")
        except Exception:
            pass
        return

    try:
        await status.delete()
    except Exception:
        pass

    kwargs = {"reply_to_message_id": src.message_id} if as_reply else {}
    await ctx.bot.send_sticker(chat.id, io.BytesIO(sticker_bytes), **kwargs)


async def q_cmd(update, ctx):
    await _quote_and_send(update, ctx, as_reply=False)


async def qr_cmd(update, ctx):
    await _quote_and_send(update, ctx, as_reply=True)


# ───────────────────────── .kang ─────────────────────────
# Unchanged: still uses Pillow + the bundled DejaVu fonts.

async def _photo_to_sticker_file(ctx, photo):
    tgfile = await ctx.bot.get_file(photo.file_id)
    raw = await tgfile.download_as_bytearray()
    im = Image.open(io.BytesIO(bytes(raw))).convert("RGBA")
    im = _fit_512(im)
    buf = io.BytesIO()
    buf.name = "kang.png"
    im.save(buf, "PNG")
    buf.seek(0)
    return buf


async def kang_cmd(update, ctx):
    msg, chat, user = update.effective_message, update.effective_chat, update.effective_user
    src = msg.reply_to_message
    if not src or not (src.sticker or src.photo):
        await say(ctx, chat.id, T("reply to a sticker or a photo with /kang to steal it into your pack."), reply_to=msg.message_id)
        return

    emoji = ctx.args[0] if ctx.args and EMOJI_RE.match(ctx.args[0]) else None
    if src.sticker:
        s = src.sticker
        file_arg = s.file_id
        fmt = "video" if s.is_video else ("animated" if s.is_animated else "static")
        emoji = emoji or s.emoji or "🤔"
    else:
        try:
            file_arg = await _photo_to_sticker_file(ctx, src.photo[-1])
        except Exception as e:
            await say(ctx, chat.id, T("couldn't read that image:") + f" {esc(e)}", reply_to=msg.message_id)
            return
        fmt = "static"
        emoji = emoji or "🤔"

    me = ctx.application.bot_data["me"]
    base = re.sub(r"[^a-zA-Z0-9_]", "", (user.username or f"u{user.id}")).lower() or f"u{user.id}"
    sticker_obj = InputSticker(sticker=file_arg, emoji_list=[emoji], format=fmt)

    async def _create(part: int):
        name = f"a{part}_{base}_by_{me.username}"
        title = f"{user.first_name or 'My'}'s Pack" + (f" {part}" if part > 1 else "")
        await ctx.bot.create_new_sticker_set(user.id, name, title[:64], stickers=[sticker_obj])
        return name

    try:
        rec = await dbase.kang_get(user.id)
        if rec and rec.get("name"):
            try:
                await ctx.bot.add_sticker_to_set(user.id, rec["name"], sticker=sticker_obj)
                name, count = rec["name"], rec.get("count", 0) + 1
                await dbase.kang_set(user.id, name, count, part=rec.get("part", 1))
            except TelegramError as e:
                s = str(e).lower()
                if "invalid" in s or "too much" in s or "too many" in s:
                    part = rec.get("part", 1) + 1
                    name = await _create(part)
                    count = 1
                    await dbase.kang_set(user.id, name, count, part=part)
                else:
                    raise
        else:
            name = await _create(1)
            count = 1
            await dbase.kang_set(user.id, name, count, part=1)
    except TelegramError as e:
        await say(ctx, chat.id, T("kang failed:") + f" {esc(e)}", reply_to=msg.message_id)
        return

    link = f"https://t.me/addstickers/{name}"
    await say(ctx, chat.id, T("✅ added to your pack ({c} stickers so far).\n{l}", c=count, l=esc(link)), reply_to=msg.message_id)


def register(app):
    dual_command(app, "q", q_cmd)
    dual_command(app, "qr", qr_cmd)
    dual_command(app, "kang", kang_cmd)
